prisma_cloud:
  username:  #access key
  password:  #secret key
  customer_name:        #optional - only needed if accessing multiple tenants
  api_base: api.prismacloud.io   #api.prismacloud.io - change as needed for your specific stack